const pool = require('../config/database');
const { authenticate, authorize } = require('../middleware/auth');
const { serverCache, clearCache } = require('../services/cacheService');
const { sanitize, generateATLCode, validateATLInput } = require('../services/utilities');
const { logAudit } = require('../services/auditService');

function setupClientRoutes(app) {
    app.get('/api/client/dashboard', authenticate, authorize('client'), async (req, res) => {
        try { const ck='client_dashboard_'+req.user.id,c=serverCache.get(ck); if(c) return res.json(c); const [a]=await pool.execute('SELECT atl.*,t.plate_no as truck_plate,t.make as truck_make FROM authority_to_load atl LEFT JOIN trucks t ON atl.truck_id=t.id WHERE atl.client_id=? ORDER BY atl.createdAt DESC LIMIT 20',[req.user.id]); const [cnt]=await pool.execute('SELECT status,COUNT(*) as count FROM authority_to_load WHERE client_id=? GROUP BY status',[req.user.id]); const s={total:0,pending:0,approved:0,dispatched:0,completed:0,cancelled:0}; cnt.forEach(x=>{if(x.status==='cancelled'||x.status==='rejected') s.cancelled+=x.count; else if(s.hasOwnProperty(x.status)) s[x.status]=x.count;}); s.total=Object.values(s).reduce((a,b)=>a+b,0); const r={status:'success',data:{stats:s,recent:a,recentATLs:a}}; serverCache.set(ck,r,30); res.json(r); } catch(e) { res.status(500).json({error:e.message}); }
    });

    app.get('/api/client/verify-truck/:plateNo', authenticate, authorize('client'), async (req, res) => {
        try { const pn=decodeURIComponent(req.params.plateNo).toUpperCase().trim(); const [t]=await pool.execute('SELECT * FROM trucks WHERE plate_no=? AND is_active=1',[pn]); if(t.length){const tr=t[0];const [d]=await pool.execute('SELECT * FROM truck_documents WHERE truck_id=?',[tr.id]);const [mr]=await pool.execute('SELECT * FROM truck_masterlist WHERE plate_no=?',[pn]);const ds={};let av=true;['lto_registration','fire_permit','dost_calibration'].forEach(ty=>{const doc=d.find(x=>x.document_type===ty);if(doc){const days=Math.ceil((new Date(doc.expiry_date)-new Date())/86400000);ds[ty]={status:days<0?'expired':days<=30?'expiring_soon':'valid',valid:days>=0,days_remaining:days,expiry_date:doc.expiry_date,document_number:doc.document_number||''};if(days<0)av=false;}else{ds[ty]={status:'missing',valid:true,days_remaining:-1};}});return res.json({status:'success',data:{truck:{id:tr.id,plate_no:tr.plate_no,make:tr.make||'Unknown',driver_name:(mr[0]?.driver_name||tr.driver_name||'').replace(/"/g,''),hauler_name:mr[0]?.hauler_name||tr.hauler_name||'',total_capacity:tr.total_capacity||0},documents:ds,can_proceed:av}});} const [m]=await pool.execute('SELECT * FROM truck_masterlist WHERE plate_no=?',[pn]); if(m.length){const mx=m[0];const ct=[mx.cot1,mx.cot2,mx.cot3,mx.cot4,mx.cot5,mx.cot6,mx.cot7,mx.cot8,mx.cot9,mx.cot10].reduce((s,v)=>s+parseFloat(v||0),0);const tc=parseFloat(mx.total_capacity)||ct||0;const [nt]=await pool.execute('INSERT INTO trucks (plate_no,make,driver_name,hauler_name,total_capacity,is_active,createdAt,updatedAt) VALUES (?,?,?,?,?,1,NOW(),NOW())',[mx.plate_no,mx.truck_make||'Unknown',(mx.driver_name||'').replace(/"/g,''),mx.hauler_name||'',tc]);return res.json({status:'success',data:{truck:{id:nt.insertId,plate_no:mx.plate_no,make:mx.truck_make||'Unknown',driver_name:(mx.driver_name||'').replace(/"/g,''),hauler_name:mx.hauler_name||'',total_capacity:tc},documents:{lto_registration:{status:'not_required',valid:true,days_remaining:999},fire_permit:{status:'not_required',valid:true,days_remaining:999},dost_calibration:{status:'not_required',valid:true,days_remaining:999}},can_proceed:true}});} res.status(404).json({status:'error',error:'Truck not found',can_proceed:false}); } catch(e) { res.status(500).json({status:'error',error:e.message,can_proceed:false}); }
    });

    app.post('/api/client/submit-atl', authenticate, authorize('client'), validateATLInput, async (req, res) => {
        try { const {truck_id,plate_no,volume,driver_name,hauler_name,remarks,company,so_number,scheduled_date,contact_number,has_si,special_instructions}=req.body; let tid=truck_id,pn=plate_no,d=driver_name,h=hauler_name; if(tid){const [t]=await pool.execute('SELECT * FROM trucks WHERE id=? AND is_active=1',[tid]);if(!t.length)return res.status(404).json({error:'Truck not found'});pn=t[0].plate_no;if(!d)d=t[0].driver_name;if(!h)h=t[0].hauler_name;const [mu]=await pool.execute('SELECT * FROM truck_masterlist WHERE plate_no=?',[pn.toUpperCase()]);if(mu.length){if(!d)d=mu[0].driver_name;if(!h)h=mu[0].hauler_name;}}else if(pn){const [t]=await pool.execute('SELECT * FROM trucks WHERE plate_no=? AND is_active=1',[pn.toUpperCase()]);if(t.length){tid=t[0].id;if(!d)d=t[0].driver_name;if(!h)h=t[0].hauler_name;}else{const [m]=await pool.execute('SELECT * FROM truck_masterlist WHERE plate_no=?',[pn.toUpperCase()]);if(m.length){const [nt]=await pool.execute('INSERT INTO trucks (plate_no,make,driver_name,hauler_name,total_capacity,is_active,createdAt,updatedAt) VALUES (?,?,?,?,?,1,NOW(),NOW())',[m[0].plate_no,m[0].truck_make||'Unknown',(m[0].driver_name||'').replace(/"/g,''),m[0].hauler_name||'',m[0].total_capacity||0]);tid=nt.insertId;if(!d)d=m[0].driver_name;if(!h)h=m[0].hauler_name;}}} if(!tid)return res.status(400).json({error:'Truck not found'}); const [ex]=await pool.execute("SELECT id FROM authority_to_load WHERE client_id=? AND truck_id=? AND status IN ('pending','approved')",[req.user.id,tid]);if(ex.length)return res.status(400).json({error:'Pending ATL exists for this truck'}); const ac=await generateATLCode(company||req.user.company_name); await pool.execute("INSERT INTO authority_to_load (atl_code,client_id,truck_id,company,so_number,volume,hauler,plate_no,driver_name,contact_number,has_si,scheduled_date,remarks,special_instructions,status,createdAt) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,'pending',NOW())",[ac,req.user.id,tid,sanitize(company||req.user.company_name,100),sanitize(so_number,50),volume,sanitize(h,100),sanitize(pn,20),sanitize(d,100),sanitize(contact_number,20),has_si||false,scheduled_date||new Date().toISOString().split('T')[0],sanitize(remarks,200),sanitize(special_instructions,500)]); serverCache.del('dispatch_enhanced_stats');serverCache.del('dispatch_truck_stats');clearCache('client_dashboard_'+req.user.id); res.status(201).json({status:'success',message:'ATL '+ac+' Submitted!',data:{atl_code:ac}}); } catch(e) { res.status(400).json({error:e.message}); }
    });

    app.post('/api/client/cancel-atl/:id', authenticate, authorize('client'), async (req, res) => {
        try { await pool.execute("UPDATE authority_to_load SET status='cancelled',remarks=? WHERE id=? AND client_id=?",['Cancellation: '+(req.body.reason||''),req.params.id,req.user.id]); await logAudit(req.user.id,'CANCEL_ATL','authority_to_load',req.params.id,{reason:req.body.reason}); res.json({status:'success',message:'Cancelled'}); } catch(e) { res.status(400).json({error:e.message}); }
    });

    app.get('/api/client/atl/:id', authenticate, authorize('client'), async (req, res) => {
        try { const [a]=await pool.execute('SELECT * FROM authority_to_load WHERE id=? AND client_id=?',[req.params.id,req.user.id]); if(!a.length) return res.status(404).json({error:'Not found'}); res.json({status:'success',data:a[0]}); } catch(e) { res.status(500).json({error:e.message}); }
    });

    app.get('/api/client/sales-orders', authenticate, authorize('client'), async (req, res) => {
        try { const [o]=await pool.execute("SELECT DISTINCT so.*,COALESCE((SELECT SUM(atl.volume) FROM authority_to_load atl WHERE atl.so_number=so.so_number AND atl.client_id=? AND atl.status NOT IN ('cancelled','rejected')),0) as client_used_volume,COALESCE((SELECT SUM(atl.volume) FROM authority_to_load atl WHERE atl.so_number=so.so_number AND atl.status NOT IN ('cancelled','rejected')),0) as total_used_volume FROM sales_orders so LEFT JOIN sales_order_clients soc ON so.id=soc.sales_order_id WHERE so.client_id=? OR soc.client_id=? ORDER BY so.createdAt DESC",[req.user.id,req.user.id,req.user.id]); res.json({status:'success',data:o.map(so=>({id:so.id,so_number:so.so_number,total_volume:parseFloat(so.total_volume)||0,used_volume:so.is_multi_client?parseFloat(so.total_used_volume):parseFloat(so.client_used_volume),remaining_volume:Math.max(0,(parseFloat(so.total_volume)||0)-(so.is_multi_client?parseFloat(so.total_used_volume):parseFloat(so.client_used_volume))),status:so.status,is_multi_client:so.is_multi_client==1,company_name:so.company_name,notes:so.notes,createdAt:so.createdAt}))}); } catch(e) { res.status(500).json({error:e.message}); }
    });
}

// Add this middleware at the top of clientController.js
async function verifyClientOwnership(req, res, next) {
    // Clients can only access their own data
    if (req.user.role === 'client') {
        const requestedClientId = req.params.id || req.body.client_id || req.query.client_id;
        if (requestedClientId && requestedClientId != req.user.id) {
            return res.status(403).json({ error: 'Access denied' });
        }
    }
    next();
}

module.exports = { setupClientRoutes };