const pool = require('../config/database');
const { authenticate, authorize } = require('../middleware/auth');
const { clearCache } = require('../services/cacheService');

function setupSalesRoutes(app) {
    app.get('/api/sales-orders/clients-list', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { const [c]=await pool.execute("SELECT id,email,company_name FROM users WHERE role='client' AND is_active=1 ORDER BY company_name ASC"); res.json({status:'success',data:c}); } catch(e) { res.status(500).json({error:e.message}); }
    });

    app.get('/api/sales-orders/validate', authenticate, async (req, res) => {
        try { const {so_number,client_id}=req.query; if(!so_number) return res.status(400).json({error:'SO required'}); const [o]=await pool.execute("SELECT so.*,u.company_name as client_company FROM sales_orders so JOIN users u ON so.client_id=u.id WHERE so.so_number=? AND so.status='active'",[so_number]); if(!o.length) return res.json({status:'error',valid:false,message:'SO not found'}); const od=o[0]; let belongs=od.client_id==client_id; if(!belongs&&od.is_multi_client){const [ac]=await pool.execute('SELECT id FROM sales_order_clients WHERE sales_order_id=? AND client_id=?',[od.id,client_id]);belongs=ac.length>0;} if(!belongs) return res.json({status:'error',valid:false,message:'SO not yours',so_owner:od.client_company}); const [u]=await pool.execute("SELECT COALESCE(SUM(volume),0) as used FROM authority_to_load WHERE so_number=? AND status NOT IN ('cancelled','rejected')",[so_number]); const t=parseFloat(od.total_volume)||0,us=parseFloat(u[0].used)||0; res.json({status:'success',valid:true,data:{so_id:od.id,so_number:od.so_number,total_volume:t,used_volume:us,remaining_volume:Math.max(0,t-us),is_multi_client:od.is_multi_client,owner_company:od.client_company}}); } catch(e) { res.status(500).json({error:e.message}); }
    });

    app.put('/api/sales-orders/sync-company-names', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { await pool.execute("UPDATE sales_orders so JOIN users u ON so.client_id=u.id SET so.company_name=u.company_name WHERE u.company_name IS NOT NULL AND u.company_name!=''"); await pool.execute("UPDATE sales_order_clients soc JOIN users u ON soc.client_id=u.id SET soc.company_name=u.company_name WHERE u.company_name IS NOT NULL AND u.company_name!=''"); res.json({status:'success',message:'Synced'}); } catch(e) { res.status(400).json({error:e.message}); }
    });

    app.get('/api/sales-orders', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { const {search,client_id,status}=req.query; let q='SELECT so.*,u.company_name as client_company,u.email as client_email FROM sales_orders so JOIN users u ON so.client_id=u.id WHERE 1=1'; const p=[]; if(search){q+=' AND (so.so_number LIKE ? OR so.company_name LIKE ?)';p.push('%'+search+'%','%'+search+'%');}if(client_id){q+=' AND so.client_id=?';p.push(client_id);}if(status){q+=' AND so.status=?';p.push(status);}q+=' ORDER BY so.createdAt DESC LIMIT 200'; const [o]=await pool.execute(q,p); const r=[]; for(const x of o){const [a]=await pool.execute('SELECT soc.*,u.company_name,u.email FROM sales_order_clients soc JOIN users u ON soc.client_id=u.id WHERE soc.sales_order_id=?',[x.id]);const [u]=await pool.execute("SELECT COALESCE(SUM(volume),0) as used FROM authority_to_load WHERE so_number=? AND status NOT IN ('cancelled','rejected')",[x.so_number]);r.push({...x,allocations:a,used_volume:parseFloat(u[0].used)});} res.json({status:'success',data:r}); } catch(e) { res.status(500).json({error:e.message}); }
    });

    app.post('/api/sales-orders', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { const {so_number,client_id,company_name,total_volume,is_multi_client,notes,allocations}=req.body; if(!so_number||!client_id) return res.status(400).json({error:'SO and Client required'}); const [ex]=await pool.execute('SELECT id FROM sales_orders WHERE so_number=? AND client_id=?',[so_number,client_id]); if(ex.length) return res.status(400).json({error:'Already exists'}); let c=company_name; if(!c){const [cl]=await pool.execute('SELECT company_name FROM users WHERE id=?',[client_id]);c=cl.length?cl[0].company_name:'';} const [r]=await pool.execute('INSERT INTO sales_orders (so_number,client_id,company_name,total_volume,is_multi_client,notes,created_by) VALUES (?,?,?,?,?,?,?)',[so_number,client_id,c,total_volume||0,is_multi_client?1:0,notes||null,req.user.id]); if(is_multi_client&&allocations&&allocations.length){for(const a of allocations){if(a.client_id&&a.allocated_volume>0){const [ac]=await pool.execute('SELECT company_name FROM users WHERE id=?',[a.client_id]);await pool.execute('INSERT INTO sales_order_clients (sales_order_id,client_id,company_name,allocated_volume) VALUES (?,?,?,?)',[r.insertId,a.client_id,ac.length?ac[0].company_name:'',a.allocated_volume]);}}} clearCache('sales_orders'); res.status(201).json({status:'success',message:'Created',data:{id:r.insertId,so_number}}); } catch(e) { res.status(400).json({error:e.message}); }
    });

    app.get('/api/sales-orders/:id', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { const [o]=await pool.execute('SELECT so.*,u.company_name as client_company,u.email as client_email FROM sales_orders so JOIN users u ON so.client_id=u.id WHERE so.id=?',[req.params.id]); if(!o.length) return res.status(404).json({error:'Not found'}); const [a]=await pool.execute('SELECT soc.*,u.company_name,u.email FROM sales_order_clients soc JOIN users u ON soc.client_id=u.id WHERE soc.sales_order_id=?',[o[0].id]); const [at]=await pool.execute('SELECT id,atl_code,company,plate_no,volume,status,client_id,createdAt FROM authority_to_load WHERE so_number=? ORDER BY createdAt DESC',[o[0].so_number]); res.json({status:'success',data:{...o[0],allocations:a,atls:at}}); } catch(e) { res.status(500).json({error:e.message}); }
    });

    app.put('/api/sales-orders/:id', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { const {total_volume,is_multi_client,notes,status,allocations}=req.body; const [ex]=await pool.execute('SELECT * FROM sales_orders WHERE id=?',[req.params.id]); if(!ex.length) return res.status(404).json({error:'Not found'}); await pool.execute('UPDATE sales_orders SET total_volume=?,is_multi_client=?,notes=?,status=? WHERE id=?',[total_volume||ex[0].total_volume,is_multi_client!==undefined?(is_multi_client?1:0):ex[0].is_multi_client,notes||ex[0].notes,status||ex[0].status,req.params.id]); if(allocations&&allocations.length){await pool.execute('DELETE FROM sales_order_clients WHERE sales_order_id=?',[req.params.id]);for(const a of allocations){if(a.client_id&&a.allocated_volume>0){const [ac]=await pool.execute('SELECT company_name FROM users WHERE id=?',[a.client_id]);await pool.execute('INSERT INTO sales_order_clients (sales_order_id,client_id,company_name,allocated_volume) VALUES (?,?,?,?)',[req.params.id,a.client_id,ac.length?ac[0].company_name:'',a.allocated_volume]);}}} clearCache('sales_orders'); res.json({status:'success',message:'Updated'}); } catch(e) { res.status(400).json({error:e.message}); }
    });

    app.delete('/api/sales-orders/:id', authenticate, authorize('dispatcher','management'), async (req, res) => {
        try { const [ex]=await pool.execute('SELECT so_number FROM sales_orders WHERE id=?',[req.params.id]); if(!ex.length) return res.status(404).json({error:'Not found'}); const [ch]=await pool.execute("SELECT COUNT(*) as count FROM authority_to_load WHERE so_number=? AND status NOT IN ('cancelled','rejected')",[ex[0].so_number]); if(ch[0].count>0) return res.status(400).json({error:'Used in '+ch[0].count+' ATLs'}); await pool.execute('DELETE FROM sales_order_clients WHERE sales_order_id=?',[req.params.id]);await pool.execute('DELETE FROM sales_orders WHERE id=?',[req.params.id]); res.json({status:'success',message:'Deleted'}); } catch(e) { res.status(400).json({error:e.message}); }
    });
}

module.exports = { setupSalesRoutes };