const BCRYPT_ROUNDS = 12;
const MAX_LOGIN_ATTEMPTS = 5;
const LOCKOUT_DURATION_MS = 15 * 60 * 1000;
const JWT_EXPIRY = '4h';
const REFRESH_TOKEN_EXPIRY = '7d';
const ALLOWED_UPDATE_FIELDS = ['tps_start', 'tps_end', 'printed_wc', 'has_si', 'so_number'];
const RECYCLE_BIN_DAYS = 30;
const AUDIT_LOG_RETENTION_DAYS = 90;

module.exports = { BCRYPT_ROUNDS, MAX_LOGIN_ATTEMPTS, LOCKOUT_DURATION_MS, JWT_EXPIRY, REFRESH_TOKEN_EXPIRY, ALLOWED_UPDATE_FIELDS, RECYCLE_BIN_DAYS, AUDIT_LOG_RETENTION_DAYS };